re_data_postgres:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: postgres
      schema: dq
      threads: 4
re_data_snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_RE_DATA_TESTING_ACCOUNT') }}"
      user: "{{ env_var('RE_DATA_TESTING_USER') }}"
      password: "{{ env_var('RE_DATA_TESTING_PASSWORD') }}"
      database: RE_DATA_TESTING
      warehouse: RE_DATA_TESTING_DWH
      schema: "{{ env_var('DQ_SCHEMA') }}"
      threads: 4
re_data_redshift:
  target: dev
  outputs:
    dev:
      type: redshift
      host: "{{ env_var('REDSHIFT_RE_DATA_TESTING_HOST') }}"
      user: "{{ env_var('RE_DATA_TESTING_USER') }}"
      password: "{{ env_var('RE_DATA_TESTING_PASSWORD') }}"
      port: 5439
      dbname: re_data_testing
      schema: "{{ env_var('DQ_SCHEMA') }}"
      threads: 4
re_data_bigquery:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account-json
      project: "{{ env_var('BIGQUERY_TESTING_PROJECT_ID') }}"
      dataset: "{{ env_var('DQ_SCHEMA') }}"
      threads: 4
      keyfile_json:
        type: "{{ env_var('BIGQUERY_TESTING_TYPE') }}"
        project_id: "{{ env_var('BIGQUERY_TESTING_PROJECT_ID') }}"
        private_key_id: "{{ env_var('BIGQUERY_TESTING_PRIVATE_KEY_ID') }}"
        private_key: "{{ env_var('BIGQUERY_TESTING_PRIVATE_KEY') }}"
        client_email: "{{ env_var('BIGQUERY_TESTING_CLIENT_EMAIL') }}"
        client_id: "{{ env_var('BIGQUERY_TESTING_CLIENT_ID') }}"
        auth_uri: "{{ env_var('BIGQUERY_TESTING_AUTH_URI') }}"
        token_uri: "{{ env_var('BIGQUERY_TESTING_TOKEN_URI') }}"
        auth_provider_x509_cert_url: "{{ env_var('BIGQUERY_TESTING_AUTH_PROVIDER_X509_CERT_URL') }}"
        client_x509_cert_url: "{{ env_var('BIGQUERY_TESTING_CLIENT_X509_CERT_URL') }}"
      location: US
      timeout_seconds: 300
      priority: interactive
      retries: 1