version: 2

models:
  - name: re_freshness
    description: >
      Information about time (in seconds) since last data was added to each table. `time_filter` column is used to find about
      time record was added. If `time_filter` column is updated, update time will also be taken into account, but be warned that in this case
      all stats computed will also take into account updated time (This maybe good or bad thing depeneding on your use case).
    
  - name: re_row_count
    description: >
      Numbers of rows added to table in specific time range. `re_data` time range is currently one day period.

  - name: re_count_nulls
    description: >
      Number of nulls in a given column for specific time range.
    
  - name: re_count_missing
    description: >
      Number of nulls and empty string values in a given column for specific time range.

  - name: re_min
    description: >
      Minimal value appearing in a given column for specific time range.

  - name: re_max
    description: >
      Maximal value appearing in a given column for specific time range.

  - name: re_avg
    description: >
      Average of all values appearing in a given column for specific time range.
    
  - name: re_min_length
    description: >
      Minimal length of all strings appearing in a given column for specific time range.

  - name: re_max_length
    description: >
      Minimal length of all strings appearing in a given column for specific time range.

  - name: re_avg_length
    description: >
      Average length of all strings appearing in a given column for specific time range.
