version: 2

models:
  - name: sanitized_user_data
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_sample_user_data')
  - name: imputed_customers_data
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_customers_imputed')
