version: 2

sources:
  - name:  "{{ var('source_schema', target.schema) }}"
    tables:
      - name: re_data_source_test_table
        columns:
          - name: number
            tests:
              - not_null
              - unique
          
          - name: description
            tests:
              - not_null
              - unique
          
      