version: 2

models:
  - name: deduplicated
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_deduplicated')
  - name: duplicates
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_duplicates')